[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.11",
    "router>=0.1",
    "routers>=0.10.1",
    "uvicorn>=0.34.0",
]
